var defaultEngines = [
	{
		"type": "searchEngine",
		"searchForm": "https://www.google.com/",
		"template": "https://www.google.com/search?q=%s",
		"icon": "http://google.com/favicon.ico",
		"title": "Google",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.amazon.com/",
		"template": "https://www.amazon.com/exec/obidos/external-search/?field-keywords=%s&ie={inputEncoding}&mode=blended",
		"icon": "https://www.amazon.com/favicon.ico",
		"title": "Amazon.com",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.facebook.com/",
		"template": "https://www.facebook.com/search/top/?q=%s&opensearch=1",
		"icon": "http://facebook.com/favicon.ico",
		"title": "Facebook",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "http://www.youtube.com",
		"template": "http://www.youtube.com/results?search_type=search_videos&search_query=%s&search_sort=relevance&search_category=0&page={startPage?}",
		"icon": "http://youtube.com/favicon.ico",
		"title": "YouTube",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://twitter.com/",
		"template": "https://twitter.com/search?q=%s&source=desktop-search",
		"icon": "http://twitter.com/favicon.ico",
		"title": "Twitter",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "http://www.pinterest.com/search/pins/",
		"template": "http://www.pinterest.com/search/pins/?q=%s",
		"icon": "http://pinterest.com/favicon.ico",
		"title": "Pinterest",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.bing.com/",
		"template": "https://www.bing.com/search?q=%s",
		"icon": "http://bing.com/favicon.ico",
		"title": "Bing",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://duckduckgo.com/",
		"template": "https://duckduckgo.com/?q=%s",
		"icon": "http://duckduckgo.com/favicon.ico",
		"title": "DuckDuckGo",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.ebay.com/",
		"template": "https://www.ebay.com/sch/i.html?_nkw=%s",
		"icon": "http://ebay.com/favicon.ico",
		"title": "eBay",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://en.wikipedia.org/",
		"template": "https://en.wikipedia.org/wiki/Special:Search?search=%s",
		"icon": "http://wikipedia.org/favicon.ico",
		"title": "Wikipedia (en)",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://lens.google.com",
		"template": "https://lens.google.com/uploadbyurl?url=%s",
		"icon": "https://lh3.googleusercontent.com/AjRsGVa7hjknlPuBARCXO_tKGNVm8C-R6gsebEWCSwgcKfp2WPkdMVovsfK_tNbNwlbBfOqJCpHS2_ejJy4iEkeJtjHKE-Xfh9crQ9hGmNNMAOT0Ua8",
		"title": "Google Lens",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 12,
		"id": gen()
	},
	{
		"type": "searchEngine",
		"searchForm": "https://www.google.com",
		"template": "https://www.google.com/search?q=site%3A%ds+%s",
		"icon": "https://www.google.com/images/branding/product/ico/googleg_lodp.ico",
		"title": "Google Site Search",
		"iconCache": "",
		"method": "GET",
		"params": [],
		"queryCharset": "UTF-8",
		"hidden": false,
		"contexts": 32,
		"id": gen()
	}
];